### ISSUE TITLE
EntityExtractor doesn't work with Rasa model evaluation

### ISSUE THREAD

**Issue by shahzadahmadmalik** [JiteshGaikwad/EntityExtractor#1]
Jitesh, i have used EntityExtractor in a chatbot. To evaluate the model i ran the RASA model evaluation tool https://rasa.com/docs/rasa/user-guide/evaluating-models/. The issue is that it gives the following error;

File "/opt/rasaVenv/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 826, in align_entity_predictions
    entities_by_extractors[p["extractor"]].append(p)
KeyError: 'MSRTExtractor'

Do you know any fix to this issue?

**Comment by JiteshGaikwad** [comment]
Hey @shahzadahmadmalik , I haven't built this for model evaluation.
